name: "Build workflow"
on:
  pull_request:
  push:
    tags:
      - v**
    branches:
      - main

env:
  CONFIG: dev
  GENESIS: genesis/dev/genesis.json

jobs:
  build-test:
    runs-on: ubuntu-20.04
    container: python:${{ matrix.python }}
    strategy:
      matrix:
        python: ['3.10']
    steps:
      - run: python3 --version
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install pip dependencies
        run: make pip-publish
      - name: build-and-test
        run: make unit-test
  run-integration-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install required os level applications
        run: |
          sudo apt update -y
          sudo apt install -y curl git nodejs python-is-python3 python3-pip
          sudo apt -y install ca-certificates curl gnupg lsb-release
          sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
          sudo echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
            $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt update
          sudo apt -y install docker-ce docker-ce-cli containerd.io
      - name: Setup docker compose
        run: |
           sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
           sudo chmod +x /usr/local/bin/docker-compose
           sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
           docker-compose --version
      - name: Check cache for Docker layers
        uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true
        with:
          key: docker-layer-caching-${{ github.workflow }}-${{ hashFiles(env.CONFIG, env.GENESIS) }}-{hash}
          restore-keys: docker-layer-caching-${{ github.workflow }}-${{ hashFiles(env.CONFIG, env.GENESIS) }}-
      - name: Create sandbox
        uses: lucasvanmol/algorand-sandbox-action@v1
        with:
          config: ${{ env.CONFIG }}
      - name: Setup integration test environment
        run: make pip-test unit-test
      - name: Run integration tests
        run: make blackbox